name: eventhorizon
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.0.0
  image_picker: ^1.0.7
  provider: ^6.0.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_countdown_timer: ^4.1.0
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  share_plus: ^4.0.10
  url_launcher: ^6.1.6
  contacts_service: ^0.6.3
  permission_handler: ^10.0.0
  cupertino_icons: ^1.0.8
  flutter_contacts: ^1.1.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
